version: "3"
services:
  mitmproxy:
    entrypoint: ["mitmdump", "-s", "/root/mockingbird/mitm/mock-response.py"]
    image: mitmproxy/mitmproxy:latest
    ports:
      - "8080:8080"
      - "0.0.0.0:8081:8081"
    stdin_open: true
    tty: true
    volumes:
      - ./certificates:/root/.mitmproxy
      - ./config:/root/mockingbird/config
      - ./mitm:/root/mockingbird/mitm
    working_dir: "/root/mockingbird"
