version: "3"
services:
  mitmproxy:
    container_name: "mitmproxy"
    entrypoint: ["mitmdump", "-s", "/root/interposer/mitm/mock-response.py"]
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    image: mitmproxy/mitmproxy:latest
    ports:
      - "8080:8080"
      - "0.0.0.0:8081:8081"
    stdin_open: true
    tty: true
    volumes:
      - ./certificates:/root/.mitmproxy
      - ./config:/root/interposer/config
      - ./mitm:/root/interposer/mitm
      - ./response:/root/interposer/response
    working_dir: "/root/interposer"
